export default {
  "index": "Introduction",
  "getting-started": "Getting started",
  "tokens": "Using tokens",
  "available-tokens": "Available tokens",
  "inspect": "Inspect & handoff",
  "dev-mode": "Dev mode",
  "styles": "Styles",
  "variables": "Variables",
  "themes": "Themes & Sets",
  "sync": "Sync",
  "transforming": "Transforming for development",
  "contributing": "Contributing",
  "troubleshooting": "Troubleshooting",
  "guides": "Guides",
}
